[common]
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -Wno-sign-compare
extra_scripts =
    pre:scripts/prepare_web_assets.py
lib_deps =
    https://github.com/tzapu/WiFiManager.git
    adafruit/Adafruit NeoPixel @ ^1.12.0
    bblanchon/ArduinoJson @ ^6.21.0
    knolleary/PubSubClient @ ^2.8

; ─────────────────────────────────────────────
;  D1 Mini — прошивка через USB
; ─────────────────────────────────────────────
[env:usb]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = ${common.monitor_speed}
board_build.flash_size = 4MB
board_build.ldscript = eagle.flash.4m2m.ld
board_build.filesystem = ${common.board_build.filesystem}
build_flags = ${common.build_flags}
extra_scripts = ${common.extra_scripts}
lib_deps = ${common.lib_deps}
